apiVersion: dbaas.opencloud.wso2.com/v1alpha1
kind: Database
metadata:
  labels:
    app.kubernetes.io/name: dbaas
    app.kubernetes.io/managed-by: kustomize
  name: database-sample
spec:
  engine: postgres
  version: "16"
  storageGB: 20
  replicas: 1
